### ISSUE TITLE
Conversion error - pH casting to INT

### ISSUE THREAD

**Issue by mwojcikowski** [bgruening/docker-recipes#15]
I was playing with conversion in OB and every conversion I tried failed due to that error

>Traceback (most recent call last):
  File "/galaxy-central/lib/galaxy/jobs/runners/__init__.py", line 163, in prepare_job
    job_wrapper.prepare()
  File "/galaxy-central/lib/galaxy/jobs/__init__.py", line 858, in prepare
    self.command_line, self.extra_filenames = tool_evaluator.build()
  File "/galaxy-central/lib/galaxy/tools/evaluation.py", line 427, in build
    raise e
ValueError: invalid literal for int() with base 10: '-1.0'

**Comment by bgruening** [comment]
@mwojcikowski thanks for the bug report! This was already fixed in: https://github.com/bgruening/galaxytools/commit/6771efaef517caf423c8b38ef46f861cf26cee89

I need to update the packages. Do you run CTB with the Docker container or did you installed it on your own?

**Comment by bgruening** [comment]
Ok, updated the Tool Shed package. Thanks!

**Comment by mwojcikowski** [comment]
It's docker container.

**Comment by bgruening** [comment]
I will rebuild this one. Thanks a bunch!
